const weatherConfig = {
  "1": {
    name: "Clear sky",
    dayColor: "#6494ED",
    nightColor: "#2C679B",
    cloudy: false,
    cloudIntensity: 0,
    rain: false,
    rainIntensity: 0,
    snow: false,
    snowIntensity: 0,
    thunder: false,
    fog: false
  },
  "2": {
    name: "Nearly clear sky",
    dayColor: "#82B5FF",
    nightColor: "#416A99",
    cloudy: false,
    cloudIntensity: 0.2,
    rain: false,
    rainIntensity: 0,
    snow: false,
    snowIntensity: 0,
    thunder: false,
    fog: false
  },
  "3": {
    name: "Variable cloudiness",
    dayColor: "#A4CCEB",
    nightColor: "#5E91B9",
    cloudy: true,
    cloudIntensity: 0.5,
    rain: false,
    rainIntensity: 0,
    snow: false,
    snowIntensity: 0,
    thunder: false,
    fog: false
  },
  "4": {
    name: "Halfclear sky",
    dayColor: "#96B5D8",
    nightColor: "#537A9B",
    cloudy: false,
    cloudIntensity: 0.3,
    rain: false,
    rainIntensity: 0,
    snow: false,
    snowIntensity: 0,
    thunder: false,
    fog: false
  },
  "5": {
    name: "Cloudy sky",
    dayColor: "#88A4B7",
    nightColor: "#465D72",
    cloudy: true,
    cloudIntensity: 0.7,
    rain: false,
    rainIntensity: 0,
    snow: false,
    snowIntensity: 0,
    thunder: false,
    fog: false
  },
  "6": {
    name: "Overcast",
    dayColor: "#9CA6B0",
    nightColor: "#4C5259",
    cloudy: true,
    cloudIntensity: 1,
    rain: false,
    rainIntensity: 0,
    snow: false,
    snowIntensity: 0,
    thunder: false,
    fog: false
  },
  "7": {
    name: "Fog",
    dayColor: "#8C8F93",
    nightColor: "#45484B",
    cloudy: false,
    cloudIntensity: 0,
    rain: false,
    rainIntensity: 0,
    snow: false,
    snowIntensity: 0,
    thunder: false,
    fog: true
  },
  "8": {
    name: "Light rain showers",
    dayColor: "#8CAFC6",
    nightColor: "#3D5F7C",
    cloudy: true,
    cloudIntensity: 0.6,
    rain: true,
    rainIntensity: 0.2,
    snow: false,
    snowIntensity: 0,
    thunder: false,
    fog: false
  },
  "9": {
    name: "Moderate rain showers",
    dayColor: "#7392AB",
    nightColor: "#2E4357",
    cloudy: true,
    cloudIntensity: 0.8,
    rain: true,
    rainIntensity: 0.5,
    snow: false,
    snowIntensity: 0,
    thunder: false,
    fog: false
  },
  "10": {
    name: "Heavy rain showers",
    dayColor: "#5C7B95",
    nightColor: "#2A3541",
    cloudy: true,
    cloudIntensity: 0.9,
    rain: true,
    rainIntensity: 0.8,
    snow: false,
    snowIntensity: 0,
    thunder: false,
    fog: false
  },
  "11": {
    name: "Thunderstorm",
    dayColor: "#4E535B",
    nightColor: "#232628",
    cloudy: true,
    cloudIntensity: 1,
    rain: true,
    rainIntensity: 1,
    snow: false,
    snowIntensity: 0,
    thunder: true,
    fog: false
  },
  "12": {
    name: "Light sleet showers",
    dayColor: "#869DAC",
    nightColor: "#3A4C61",
    cloudy: true,
    cloudIntensity: 0.6,
    rain: true,
    rainIntensity: 0.2,
    snow: true,
    snowIntensity: 0.2,
    thunder: false,
    fog: false
  },
  "13": {
    name: "Moderate sleet showers",
    dayColor: "#75869A",
    nightColor: "#354553",
    cloudy: true,
    cloudIntensity: 0.8,
    rain: true,
    rainIntensity: 0.5,
    snow: true,
    snowIntensity: 0.5,
    thunder: false,
    fog: false
  },
  "14": {
    name: "Heavy sleet showers",
    dayColor: "#5F7483",
    nightColor: "#2D3843",
    cloudy: true,
    cloudIntensity: 0.9,
    rain: true,
    rainIntensity: 0.8,
    snow: true,
    snowIntensity: 0.8,
    thunder: false,
    fog: false
  },
  "15": {
    name: "Light snow showers",
    dayColor: "#AFC6DA",
    nightColor: "#4C647C",
    cloudy: true,
    cloudIntensity: 0.6,
    rain: false,
    rainIntensity: 0,
    snow: true,
    snowIntensity: 0.2,
    thunder: false,
    fog: false
  },
  "16": {
    name: "Moderate snow showers",
    dayColor: "#93AEBD",
    nightColor: "#42576A",
    cloudy: true,
    cloudIntensity: 0.8,
    rain: false,
    rainIntensity: 0,
    snow: true,
    snowIntensity: 0.5,
    thunder: false,
    fog: false
  },
  "17": {
    name: "Heavy snow showers",
    dayColor: "#7A94A8",
    nightColor: "#3B4C5C",
    cloudy: true,
    cloudIntensity: 0.9,
    rain: false,
    rainIntensity: 0,
    snow: true,
    snowIntensity: 0.8,
    thunder: false,
    fog: false
  },
  "18": {
    name: "Light rain",
    dayColor: "#8CAFC6",
    nightColor: "#3D5F7C",
    cloudy: true,
    cloudIntensity: 0.6,
    rain: true,
    rainIntensity: 0.2,
    snow: false,
    snowIntensity: 0,
    thunder: false,
    fog: false
  },
  "19": {
    name: "Moderate rain",
    dayColor: "#7391A6",
    nightColor: "#35465A",
    cloudy: true,
    cloudIntensity: 0.8,
    rain: true,
    rainIntensity: 0.5,
    snow: false,
    snowIntensity: 0,
    thunder: false,
    fog: false
  },
  "20": {
    name: "Heavy rain",
    dayColor: "#5C7B95",
    nightColor: "#2A3541",
    cloudy: true,
    cloudIntensity: 0.9,
    rain: true,
    rainIntensity: 0.8,
    snow: false,
    snowIntensity: 0,
    thunder: false,
    fog: false
  },
  "21": {
    name: "Thunder",
    dayColor: "#4E535B",
    nightColor: "#232628",
    cloudy: true,
    cloudIntensity: 1,
    rain: false,
    rainIntensity: 0,
    snow: false,
    snowIntensity: 0,
    thunder: true,
    fog: false
  },
  "22": {
    name: "Light sleet",
    dayColor: "#869DAC",
    nightColor: "#3A4C61",
    cloudy: true,
    cloudIntensity: 0.6,
    rain: true,
    rainIntensity: 0.2,
    snow: true,
    snowIntensity: 0.2,
    thunder: false,
    fog: false
  },
  "23": {
    name: "Moderate sleet",
    dayColor: "#75869A",
    nightColor: "#354553",
    cloudy: true,
    cloudIntensity: 0.8,
    rain: true,
    rainIntensity: 0.5,
    snow: true,
    snowIntensity: 0.5,
    thunder: false,
    fog: false
  },
  "24": {
    name: "Heavy sleet",
    dayColor: "#5F7483",
    nightColor: "#2D3843",
    cloudy: true,
    cloudIntensity: 0.9,
    rain: true,
    rainIntensity: 0.8,
    snow: true,
    snowIntensity: 0.8,
    thunder: false,
    fog: false
  },
  "25": {
    name: "Light snowfall",
    dayColor: "#AFC6DA",
    nightColor: "#4C647C",
    cloudy: true,
    cloudIntensity: 0.6,
    rain: false,
    rainIntensity: 0,
    snow: true,
    snowIntensity: 0.2,
    thunder: false,
    fog: false
  },
  "26": {
    name: "Moderate snowfall",
    dayColor: "#93AEBD",
    nightColor: "#42576A",
    cloudy: true,
    cloudIntensity: 0.8,
    rain: false,
    rainIntensity: 0,
    snow: true,
    snowIntensity: 0.5,
    thunder: false,
    fog: false
  },
  "27": {
    name: "Heavy snowfall",
    dayColor: "#7A94A8",
    nightColor: "#3B4C5C",
    cloudy: true,
    cloudIntensity: 0.9,
    rain: false,
    rainIntensity: 0,
    snow: true,
    snowIntensity: 0.8,
    thunder: false,
    fog: false
  },
  "28": {
    name: "Thunderstorm with rain",
    dayColor: "#5C6A7B",
    nightColor: "#2A3139",
    cloudy: true,
    cloudIntensity: 1,
    rain: true,
    rainIntensity: 1,
    snow: false,
    snowIntensity: 0,
    thunder: true,
    fog: false
  },
  "29": {
    name: "Thunderstorm with sleet",
    dayColor: "#5C6A7B",
    nightColor: "#2A3139",
    cloudy: true,
    cloudIntensity: 1,
    rain: true,
    rainIntensity: 1,
    snow: true,
    snowIntensity: 0.8,
    thunder: true,
    fog: false
  },
  "30": {
    name: "Thunderstorm with snow",
    dayColor: "#5C6A7B",
    nightColor: "#2A3139",
    cloudy: true,
    cloudIntensity: 1,
    rain: false,
    rainIntensity: 0,
    snow: true,
    snowIntensity: 0.8,
    thunder: true,
    fog: false
  }
};
export default weatherConfig; 